### ISSUE TITLE
SQLITE_BUSY: database is locked

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/virtual-things-adapter#51]
Saw this error in the log:

2019-11-21 23:25:39.010 ERROR  : virtual-things: events.js:183
2019-11-21 23:25:39.011 ERROR  : virtual-things:       throw er; // Unhandled 'error' event
2019-11-21 23:25:39.012 ERROR  : virtual-things:       ^
2019-11-21 23:25:39.014 ERROR  : virtual-things: 
2019-11-21 23:25:39.015 ERROR  : virtual-things: Error: SQLITE_BUSY: database is locked
2019-11-21 23:25:39.021 INFO   : Plugin: virtual-things-adapter died, code = 1 restarting after 0

**Comment by flatsiedatsie** [comment]
Also, noticed earlier that removing things was taking VERY long. I even made a gif, but of course when I made it it wasn't so bad.

![removing-slow](https://user-images.githubusercontent.com/805405/69382236-885f2100-0cae-11ea-970a-948b23f06a14.gif)

**Comment by flatsiedatsie** [comment]
Tried to disable it in the add-ons list. It was stuck on the highlighted state for a very long time. Then I checked in the logs:
```
2019-11-21 23:40:14.442 INFO   : Unloading VirtualThingsAdapter
2019-11-21 23:40:14.451 ERROR  : virtual-things: /home/pi/.mozilla-iot/addons/virtual-things-adapter/virtual-things-adapter.js:1477
2019-11-21 23:40:14.453 ERROR  : virtual-things:     if (this.config.randomizePropertyValues) {
2019-11-21 23:40:14.455 ERROR  : virtual-things:                     ^
2019-11-21 23:40:14.456 ERROR  : virtual-things: 
2019-11-21 23:40:14.458 ERROR  : virtual-things: TypeError: Cannot read property 'randomizePropertyValues' of undefined
2019-11-21 23:40:14.459 ERROR  : virtual-things:     at VirtualThingsAdapter.unload (/home/pi/.mozilla-iot/addons/virtual-things-adapter/virtual-things-adapter.js:1477:21)
2019-11-21 23:40:14.460 ERROR  : virtual-things:     at AddonManagerProxy.onMsg (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/addon-manager-proxy.js:320:17)
2019-11-21 23:40:14.461 ERROR  : virtual-things:     at IpcSocket.onData (/home/pi/mozilla-iot/gateway/node_modules/gateway-addon/lib/ipc.js:171:10)
2019-11-21 23:40:14.463 ERROR  : virtual-things:     at emitOne (events.js:116:13)
2019-11-21 23:40:14.464 ERROR  : virtual-things:     at Socket.emit (events.js:211:7)
2019-11-21 23:40:14.466 ERROR  : virtual-things:     at addChunk (_stream_readable.js:263:12)
2019-11-21 23:40:14.467 ERROR  : virtual-things:     at readableAddChunk (_stream_readable.js:250:11)
2019-11-21 23:40:14.469 ERROR  : virtual-things:     at Socket.Readable.push (_stream_readable.js:208:10)
2019-11-21 23:40:14.470 ERROR  : virtual-things:     at Socket._receive (/home/pi/mozilla-iot/gateway/node_modules/nanomsg/lib/index.js:204:8)
2019-11-21 23:40:14.471 ERROR  : virtual-things:     at Socket.<anonymous> (/home/pi/mozilla-iot/gateway/node_modules/nanomsg/lib/index.js:218:24)
2019-11-21 23:40:14.481 INFO   : Plugin: virtual-things-adapter died, code = 1 restarting after 0
```
